#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jun 22 11:54:48 +07 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_axi4_uart_time_impl -key {Post-Implementation:sim_1:Timing:tb_axi4_uart} -tclbatch tb_axi4_uart.tcl -log simulate.log"
xsim tb_axi4_uart_time_impl -key {Post-Implementation:sim_1:Timing:tb_axi4_uart} -tclbatch tb_axi4_uart.tcl -log simulate.log

